[project]
name = "data-agents-on-the-lakehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bauplan>=0.0.3a395",
    "boto3>=1.38.36",
    "e2b-code-interpreter>=1.5.1",
    "litellm>=1.72.4",
]
